# pubspec.yaml
name: sports_quiz
description: MVP Football Quiz app (Flutter)
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (aligned versions)
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_analytics: ^12.0.3

  # Local storage / utils
  sqflite: ^2.4.0
  path: ^1.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/db/schema.sql
