// lib/services/firebase_service.dart
//
// PURPOSE:
//  - Centralized service to handle Firebase initialization and authentication.
//  - Keeps Firebase setup logic separate from UI code.
//  - Provides simple methods: signIn, signUp, signOut, and a user stream for UI updates.

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../firebase_options.dart'; // Auto-generated by `flutterfire configure`.

class FirebaseService {
  // ✅ Singleton pattern ensures a single instance across the app.
  static final FirebaseService I = FirebaseService._();
  FirebaseService._();

  /// Initializes Firebase once before running the app.
  /// This ensures Firebase APIs can be used safely anywhere after startup.
  Future<void> init() async {
    // Avoid re-initialization if already set up (e.g., on hot reload).
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }
  }

  /// ✅ Stream that emits the current user whenever sign-in state changes.
  Stream<User?> authState() => FirebaseAuth.instance.authStateChanges();

  /// ✅ Create a new user account with email and password.
  Future<UserCredential> signUp({
    required String email,
    required String password,
  }) {
    return FirebaseAuth.instance.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );
  }

  /// ✅ Sign in an existing user with email and password.
  Future<UserCredential> signIn({
    required String email,
    required String password,
  }) {
    return FirebaseAuth.instance.signInWithEmailAndPassword(
      email: email,
      password: password,
    );
  }

  /// ✅ Sign out the current user.
  Future<void> signOut() => FirebaseAuth.instance.signOut();

  /// ✅ Convenience getter for accessing the currently signed-in user.
  User? get currentUser => FirebaseAuth.instance.currentUser;
}
