// lib/services/firebase_service.dart
//
// PURPOSE:
//  - Centralized service to handle Firebase initialization, authentication, and analytics.
//  - Keeps Firebase setup logic separate from UI code.
//  - Provides simple methods for signIn, signUp, signOut, user state stream, and analytics events.

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import '../firebase_options.dart'; // Auto-generated by `flutterfire configure`.

class FirebaseService {
  // ✅ Singleton pattern ensures a single instance across the app.
  static final FirebaseService I = FirebaseService._();
  FirebaseService._();

  FirebaseAnalytics? _analytics;

  /// Initializes Firebase once before running the app.
  /// Ensures Firebase APIs (Auth, Firestore, Analytics) can be used safely anywhere after startup.
  Future<void> init() async {
    // Avoid re-initialization if already set up (e.g., during hot reload).
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }

    // Initialize analytics instance
    _analytics = FirebaseAnalytics.instance;
  }

  // ---------------------------------------------------------------------------
  // 🔹 AUTHENTICATION
  // ---------------------------------------------------------------------------

  /// Stream that emits the current user whenever sign-in state changes.
  Stream<User?> authState() => FirebaseAuth.instance.authStateChanges();

  /// Create a new user account with email and password.
  Future<UserCredential> signUp({
    required String email,
    required String password,
  }) {
    return FirebaseAuth.instance.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );
  }

  /// Sign in an existing user with email and password.
  Future<UserCredential> signIn({
    required String email,
    required String password,
  }) {
    return FirebaseAuth.instance.signInWithEmailAndPassword(
      email: email,
      password: password,
    );
  }

  /// Sign in anonymously (optional, mainly for admin analytics or guest flow).
  Future<UserCredential?> signInAnonymously() async {
    try {
      final credential = await FirebaseAuth.instance.signInAnonymously();
      await logLoginAnonymous();
      return credential;
    } catch (e) {
      // ignore: avoid_print
      print('Anonymous login failed: $e');
      return null;
    }
  }

  /// Sign out the current user.
  Future<void> signOut() => FirebaseAuth.instance.signOut();

  /// Convenience getter for accessing the currently signed-in user.
  User? get currentUser => FirebaseAuth.instance.currentUser;

  // ---------------------------------------------------------------------------
  // 🔹 ANALYTICS
  // ---------------------------------------------------------------------------

  /// Log that the Global Quiz list was viewed.
  Future<void> logQuizListViewed() async {
    try {
      await _analytics?.logEvent(name: 'quiz_list_viewed');
    } catch (e) {
      // ignore: avoid_print
      print('Analytics logQuizListViewed failed: $e');
    }
  }

  /// Log that a quiz was tapped (opened or selected).
  Future<void> logQuizTapped({
    required String quizId,
    required String title,
  }) async {
    try {
      await _analytics?.logEvent(
        name: 'quiz_tapped',
        parameters: <String, Object>{
          'quiz_id': quizId,
          'title': title,
        },
      );
    } catch (e) {
      // ignore: avoid_print
      print('Analytics logQuizTapped failed: $e');
    }
  }

  /// Log when an anonymous login succeeds (for admins or test users).
  Future<void> logLoginAnonymous() async {
    try {
      await _analytics?.logEvent(name: 'login_anonymous');
    } catch (e) {
      // ignore: avoid_print
      print('Analytics logLoginAnonymous failed: $e');
    }
  }

  /// Log any custom analytics event.
  /// Accepts nullable values, drops nulls, and casts to the exact type Analytics expects.
  Future<void> logCustomEvent({
    required String name,
    Map<String, Object?>? parameters,
  }) async {
    try {
      final sanitized = _sanitizeParams(parameters);
      await _analytics?.logEvent(name: name, parameters: sanitized);
    } catch (e) {
      // ignore: avoid_print
      print('Analytics custom log failed: $e');
    }
  }

  /// Force flush events (useful during debug/testing).
  Future<void> flushAnalytics() async {
    try {
      await _analytics?.logEvent(name: 'flush_triggered');
    } catch (_) {}
  }

  // ---------------------------------------------------------------------------
  // 🔹 UTILITIES
  // ---------------------------------------------------------------------------

  /// Simple helper to print current user info for debug purposes.
  void debugPrintCurrentUser() {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      // ignore: avoid_print
      print('No user currently signed in.');
    } else {
      // ignore: avoid_print
      print('Signed in as ${user.uid} (${user.isAnonymous ? "anonymous" : user.email})');
    }
  }

  /// Convert Map<String, Object?>? to Map<String, Object> by removing nulls
  /// and allowing only primitive types supported by Analytics.
  Map<String, Object>? _sanitizeParams(Map<String, Object?>? src) {
    if (src == null) return null;
    final out = <String, Object>{};
    src.forEach((key, value) {
      if (value == null) return;
      // Firebase Analytics supports num, String, and bool as parameter values.
      if (value is num || value is String || value is bool) {
        out[key] = value;
      } else {
        // Fallback: stringify unsupported types
        out[key] = value.toString();
      }
    });
    return out;
  }
}
